---
title: "ESM 244 Lab Week 1"
author: "Kirsten Hodgson"
date: "1/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(sf)
library(tmap)
```

### Read in SF trees data

```{r}
sf_trees <- read.csv(here("data", "sf_trees", "sf_trees.csv"))
```

### Basic wrangling reminders

Refresh some skills for data wrangling & summary statistics using functions in the `dplyr` package.

Find the top 5 highest observations of trees by legal_status, do some wrangling, make a graph.

```{r}
top_5_status <- sf_trees %>% 
  count(legal_status) %>% 
  drop_na(legal_status) %>% 
  rename(tree_count = n) %>% 
  relocate(tree_count) %>% 
  slice_max(tree_count, n = 5)
```

Make a graph of top 5 observations by legal status

```{r}
ggplot(data = top_5_status, aes(x = fct_reorder(legal_status, tree_count), 
                                y = tree_count)) +
  geom_col() +
  labs(x = "Legal Status\n", y = "\nTree Count") +
  coord_flip() +
  theme_minimal()
```

